<?php

namespace Database\Seeders;

use App\Models\KbArticle;
use Illuminate\Database\Seeder;

class KbArticleSeeder extends Seeder
{
    public function run(): void
    {
        KbArticle::truncate();
        
        $nowStr = now()->format('Y-m-d H:i:s');

        KbArticle::create([
            'title'            => 'How to Enable Multi-Factor Authentication (MFA)',
            'meta_description' => 'Learn how to secure your support account by enabling multi-factor authentication (MFA).',
            'seo_link'         => 'how-to-enable-mfa',
            'category_id'      => 1,
            'article_content'  => '<p>Keeping your support account secure is our top priority. We highly recommend enabling Multi-Factor Authentication (MFA) to prevent unauthorized access.</p>
<h2>What is Multi-Factor Authentication?</h2>
<p>Multi-Factor Authentication (MFA) is a security process where a user provides two different authentication factors to verify themselves. This adds an extra layer of protection on top of your standard password.</p>
<h2>Step-by-Step Instructions</h2>
<ol>
<li><strong>Log in</strong> to your helpdesk account.</li>
<li>Click on your profile name in the upper-right corner and select <strong>My Profile</strong> or <strong>Settings</strong>.</li>
<li>Locate the <strong>Security Settings</strong> section.</li>
<li>Click on <strong>Enable MFA</strong>.</li>
<li>Open your preferred authenticator app (such as <em>Google Authenticator</em>, <em>Microsoft Authenticator</em>, or <em>1Password</em>) on your mobile device.</li>
<li>Scan the QR code displayed on your screen.</li>
<li>Enter the 6-digit verification code generated by the authenticator app.</li>
<li>Click <strong>Verify and Save</strong>.</li>
</ol>
<blockquote><p><strong>Note:</strong> We recommend saving the backup recovery codes provided. If you ever lose access to your authenticator app, these recovery codes will be the only way to access your account.</p></blockquote>
<p>If you encounter any issues during this setup, please open a support ticket immediately.</p>',
            'article_active'   => 1,
            'date_added'       => $nowStr,
            'date_modified'    => $nowStr,
        ]);

        KbArticle::create([
            'title'            => 'Troubleshooting Email Ticket Replies',
            'meta_description' => 'Having trouble replying to support tickets via email? Read this troubleshooting guide to resolve issues with reply tokens.',
            'seo_link'         => 'troubleshooting-email-ticket-replies',
            'category_id'      => 2,
            'article_content'  => '<p>Our ticketing system allows you to respond directly to tickets via email. When a support agent updates your ticket, you\'ll receive an email notification. You can simply reply to that email, and your response will be automatically appended to the ticket.</p>
<p>If your replies are not appearing on the dashboard, please review the troubleshooting steps below.</p>
<h3>1. Do Not Alter the Subject Line</h3>
<p>Our email parser relies on the unique <strong>Ticket ID</strong> and <strong>Reply Token</strong> embedded in the subject line (e.g., <code>[Ticket #12345] [Token: abcd1234]</code>). If you modify, delete, or rewrite the subject line, our system will fail to associate your reply with the correct ticket.</p>
<h3>2. Reply from the Registered Email Address</h3>
<p>You must reply using the exact email address associated with your helpdesk account. For security reasons, replies received from unregistered or unauthorized email addresses are automatically rejected.</p>
<h3>3. Check for Email Signature Formatting</h3>
<p>To ensure your reply is parsed cleanly, keep your response <strong>above the reply header</strong> line:<br>
<code>--- Reply ABOVE THIS LINE to update your ticket ---</code></p>
<p>Any text placed below this marker is ignored by the parser.</p>
<pre><code>--- Example Reply ---
Hi Support Team, 

The issue has been resolved. Thanks for your help!

--- Reply ABOVE THIS LINE to update your ticket ---
</code></pre>
<p>If you have verified all the steps above and your replies are still not appearing, please submit a guest support request or contact your system administrator.</p>',
            'article_active'   => 1,
            'date_added'       => $nowStr,
            'date_modified'    => $nowStr,
        ]);

        KbArticle::create([
            'title'            => 'Supported File Formats and Attachment Limits',
            'meta_description' => 'Detailed list of allowed file formats and maximum upload size limits when attaching files to a support ticket.',
            'seo_link'         => 'supported-file-formats-and-limits',
            'category_id'      => 1,
            'article_content'  => '<p>When submitting a support ticket or replying to one, you can upload screenshots, configuration logs, or documents to help our team diagnose the issue faster.</p>
<p>To maintain system stability and security, we enforce certain file restrictions.</p>
<h3>Upload Limits</h3>
<ul>
<li><strong>Maximum File Size:</strong> 10MB per file.</li>
<li><strong>Maximum Files per Request:</strong> 3 files.</li>
</ul>
<h3>Supported File Formats</h3>
<table>
<thead>
<tr>
<th style="text-align: left;">File Type</th>
<th style="text-align: left;">Allowed Extensions</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;"><strong>Images</strong></td>
<td style="text-align: left;"><code>.png</code>, <code>.jpg</code>, <code>.jpeg</code>, <code>.gif</code></td>
<td style="text-align: left;">Screenshots and diagrams</td>
</tr>
<tr>
<td style="text-align: left;"><strong>Documents</strong></td>
<td style="text-align: left;"><code>.pdf</code>, <code>.docx</code>, <code>.txt</code>, <code>.csv</code></td>
<td style="text-align: left;">Configuration reports or manuals</td>
</tr>
<tr>
<td style="text-align: left;"><strong>Archives</strong></td>
<td style="text-align: left;"><code>.zip</code>, <code>.tar.gz</code></td>
<td style="text-align: left;">Grouped configuration files</td>
</tr>
<tr>
<td style="text-align: left;"><strong>Logs</strong></td>
<td style="text-align: left;"><code>.log</code></td>
<td style="text-align: left;">Diagnostic server logs</td>
</tr>
</tbody>
</table>
<h3>Prohibited Files</h3>
<p>For security reasons, we do <strong>not</strong> allow uploads of executable files, scripts, or installer formats (e.g., <code>.exe</code>, <code>.bat</code>, <code>.sh</code>, <code>.msi</code>, <code>.js</code>).</p>
<p>If you need to share code snippets, please paste them directly into the description using code blocks:</p>
<pre><code class="language-json">{
  "status": "error",
  "message": "Database connection timed out"
}
</code></pre>
<p>If your file is larger than 10MB, please upload it to a secure cloud storage provider (like Google Drive, Dropbox, or OneDrive) and share the link with us.</p>',
            'article_active'   => 1,
            'date_added'       => $nowStr,
            'date_modified'    => $nowStr,
        ]);

        KbArticle::create([
            'title'            => 'Billing Cycles and Duplicate Charge Questions',
            'meta_description' => 'Frequently asked questions about monthly billing cycles, duplicate charges, and invoice details.',
            'seo_link'         => 'billing-cycles-and-duplicate-charges',
            'category_id'      => 3,
            'article_content'  => '<p>Here you will find answers to the most common questions regarding subscription payments, invoice dates, and billing issues.</p>
<h2>1. When will I be billed?</h2>
<p>Your subscription is billed on a recurring monthly or annual cycle, starting on the day you upgrade to a paid plan. <br>
<em>Example:</em> If you sign up on January 15th, your billing date will be the 15th of every subsequent month.</p>
<h2>2. Why do I see a duplicate charge on my statement?</h2>
<p>If you see two identical charges on your credit card or bank statement, it is usually due to one of the following reasons:</p>
<ol>
<li><strong>Authorization Hold:</strong> When a payment is processed, your bank may place a temporary authorization hold. This hold will usually drop off automatically within 3 to 5 business days, leaving only the actual settled charge.</li>
<li><strong>Multiple Accounts:</strong> Check if you have created a second workspace or upgraded another account.</li>
<li><strong>Plan Changes:</strong> If you change your plan in the middle of a billing cycle, you may see a prorated charge alongside your standard charge.</li>
</ol>
<h2>3. How do I request a refund?</h2>
<p>If you believe you have been charged in error, please contact our billing department by submitting a ticket under the <strong>Billing &amp; Invoices</strong> department.</p>
<p>Include the following details:</p>
<ul>
<li>The last 4 digits of the card charged</li>
<li>Transaction date and amount</li>
<li>Invoice number (found in your billing settings)</li>
</ul>
<p>All refund requests are reviewed within 48 hours.</p>',
            'article_active'   => 1,
            'date_added'       => $nowStr,
            'date_modified'    => $nowStr,
        ]);

        KbArticle::create([
            'title'            => 'Draft Article Example (Hidden)',
            'meta_description' => 'This is a sample draft article that is marked as inactive and should not be visible to the public.',
            'seo_link'         => 'draft-article-example-hidden',
            'category_id'      => 4,
            'article_content'  => '<p>This article is a draft. It should not be listed on the public landing page, nor should it be reachable at <code>/kb/draft-article-example-hidden</code> for non-authenticated public users.</p>',
            'article_active'   => 0,
            'date_added'       => $nowStr,
            'date_modified'    => $nowStr,
        ]);
    }
}
